--- 
default: 
  adapter: postgresql
  encoding: unicode
  pool: 5
development: 
  adapter: postgresql
  database: receta_development
  encoding: unicode
  password: ngpassword
  pool: 5
production: 
  adapter: postgresql
  database: receta_production
  encoding: unicode
  password: "<%= ENV['RECETA_DATABASE_PASSWORD'] %>"
  pool: 5
  username: receta
test: 
  adapter: postgresql
  database: receta_test
  encoding: unicode
  pool: 5
